[#236] 로깅 기능 세팅
woowacourse-teams/2021-pick-git pull request #237
Opened 2021-07-21 11:00 UTC by xlffm3

## 상세 내용

상세 내용 작성 중입니다,, 추후에 리뷰 요청할게요

## 기타

2021-07-22 05:57 UTC, bperhaps approved these changes
좋네... 결국은 XML 노가다가 답이었구나. yaml로 어느정도 컨트롤 가능할거라고 생각했는데 그건 아닌가보네..

질문이 있다면, test의 경우로 로그를 남겨야 할까? 나는 test는 콘솔 출력만으로 충분할 것 같은데... 테스트 코드 한번 돌릴 때 마다 파일 생기는게 맞는가 하는 생각이 들어서. 어케 생각해?

2021-07-22 05:57 UTC, bperhaps commented on backend/pick-git/build.gradle
> +
이거 머지할때 기존 롬복이랑 충돌 안나려나? 의존성 2개 생길것같은데..
리베이스 함 하는게 좋을듯?

2021-07-22 05:57 UTC, bperhaps commented on s3-proxy/s3-proxy/src/main/java/com/woowacourse/s3proxy/exception/ExceptionAdvice.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ExceptionAdvice.class);
우리 롬복 쓰는데 어노테이션으로 하자

2021-07-22 07:03 UTC, xlffm3 commented on backend/pick-git/build.gradle
> +
제가 pr 올린 시점이 병합 전이라서 현재 conflict 납니다.

2021-07-22 07:04 UTC, xlffm3 commented on s3-proxy/s3-proxy/src/main/java/com/woowacourse/s3proxy/exception/ExceptionAdvice.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ExceptionAdvice.class);
s3쪽도 의존성 추가할까요 그럼?

2021-07-22 07:04 UTC, bperhaps commented on s3-proxy/s3-proxy/src/main/java/com/woowacourse/s3proxy/exception/ExceptionAdvice.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ExceptionAdvice.class);
난 좋아!

2021-07-22 07:04 UTC, bperhaps commented on backend/pick-git/build.gradle
> +
얏빠리구만

2021-07-22 07:09 UTC, xlffm3 commented on backend/pick-git/build.gradle
> +
@bperhaps aws 우분투와 같은 배포 환경에서 종종 테스트는 경우 디버그할 필요가 없다면 콘솔로 변경할게요.

2021-07-22 07:10 UTC, bperhaps commented on backend/pick-git/build.gradle
> +
지금 CICD가 동작하고 있어서 운영, 개발 서버에서 test로 작동시킬 일은 없을것 같다는 판단이야!!

2021-07-22 07:12 UTC, xlffm3 commented on backend/pick-git/build.gradle
> +
근데 이부분은 백엔드 회의가 필요하겠네요 로깅 전략

2021-07-22 07:13 UTC, bperhaps commented on backend/pick-git/build.gradle
> +
인정..... 지금 톡방에 올려볼께

2021-07-22 07:30 UTC, da-nyee commented on backend/pick-git/build.gradle
> +
testCompileOnly로 선언된 건 testCompileClassPath로 의존성 추가돼서 딱히 충돌날 일 없을 거 같아요

2021-07-22 07:54 UTC, da-nyee requested changes
케빈 수고하셨습니다 👍

API 로그도 `logback-access.xml`로 남기는 의견 찬성합니다!
이 부분 반영하면 그때 다시 리뷰할게요.

제가 예전에 미션에서 받았던 [서버 환경에 따른 로그 레벨 정도](https://github.com/woowacourse/atdd-subway-map/pull/77#discussion_r627190606) 관련 피드백 첨부합니다.
참고하면 좋을 거 같아요.

코멘트 남긴 거 확인해주세요!

2021-07-22 07:54 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/GlobalExceptionHandler.java
> +        log.error("로그인 실패 " + errorCode);
여기까지는 ERROR 레벨이고 아래부터는 WARN 레벨인데, 이 클래스 내에서 차이를 둔 이유가 있나요?

2021-07-22 07:54 UTC, da-nyee commented on backend/pick-git/src/main/resources/logback-spring.xml
> +    <logger name="org.hibernate.tool.hbm2ddl" level="DEBUG">
```suggestion
    <logger name="org.hibernate.tool.hbm2ddl" level="INFO">
```

운영 서버는 보통 INFO 레벨까지 로그를 찍는다고 들었어요. 이 부분 INFO로 변경해도 괜찮을 거 같아요

2021-07-22 07:54 UTC, da-nyee commented on backend/pick-git/src/main/resources/logback-spring.xml
> +  <springProfile name="test">
테스트 환경은 TRACE 레벨까지 다 찍는 게 낫지 않을까요?
파일 말고 콘솔 출력 의견 동의합니다!

2021-07-22 07:54 UTC, da-nyee commented on s3-proxy/s3-proxy/src/main/resources/logback-spring.xml
> +  <springProfile name="test">
여기도 테스트 환경은 TRACE 레벨로 하는 게 어떨까 싶어요!

2021-07-22 07:55 UTC, da-nyee commented on backend/pick-git/src/main/resources/logback-spring.xml
> +    <logger name="org.hibernate.tool.hbm2ddl" level="DEBUG">
아 근데 이거는 팀원들이랑 로깅 전략 논의해서 결정하는 게 나을 거 같네요!

2021-07-22 08:54 UTC, yjksw approved these changes
로깅도 깔끔하게 적용이 잘 되었네요~~ 의견합의가 필요한 세부적인 조정 외에 모두 좋아서 바로 approve 합니다!!

2021-07-22 08:54 UTC, yjksw commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/GlobalExceptionHandler.java
> +        log.error("로그인 실패 " + errorCode);
엇 이 부분이 왜 authenticationException으로 되어 있을까유..? 로그인 관련 말고도 ApplicationException이  pickgit에 커스템 예외를 다 처리하도록 했었던 것 같아요. 제가 잘못 이해하고 있을수도 있으니 한번 확인해보면 좋겠네요!! 그러면 로그에 찍힐때도 로그인 실패로 기입하는 것도 수정해야겠네요.

2021-07-22 08:54 UTC, yjksw commented on backend/pick-git/src/main/resources/logback-spring.xml
> +    <logger name="org.hibernate.tool.hbm2ddl" level="DEBUG">
다니랑 동의합니다~

2021-07-22 09:33 UTC, binghe819 approved these changes
케빈 고생 많았어요~~ 👍 

로깅 전략은 같이 토론하여 정하면 될 듯합니다!

그리고 케빈이 노션에 정리한 글과 레포에 학습 테스트 덕분에 로깅 따라해볼 수 있어서 좋았어요 :) 감사합니다~

2021-07-22 09:33 UTC, binghe819 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/GlobalExceptionHandler.java
> +        log.error("로그인 실패 " + errorCode);
앗! 이전에 예외처리 전략 이슈때 메서드명을 수정하지 않아서 케빈이 헷갈린듯합니다! (죄송해요ㅠㅎ)

`ApplicationException`예외를 잡는 부분이라 로그인 예외말고도 여러 도메인 예외를 처리합니다!

메서드명이랑 로깅 내용을 수정하는 것이 좋을 것 같아요!

2021-07-22 14:40 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/GlobalExceptionHandler.java
> +        log.error("로그인 실패 " + errorCode);
사용자 요청 수행에 실패했을 때는 error,
그 외의 경우는 사용자 요청에 기인하기 보다는 서버 내부적인 문제에서 발생하는 것들이라 warn을 두었는데요

https://mdj1234.tistory.com/63
와 같은 내용들을 기반으로 작성했습니다

다만 로그를 제대로 사용해보질 않아서 이게 info로 둬도 되는지 모르겠습니다

2021-07-22 15:25 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/GlobalExceptionHandler.java
> +        log.error("로그인 실패 " + errorCode);
앗 이부분 제가 수정했어요!

2021-07-22 15:26 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/GlobalExceptionHandler.java
> +        log.error("로그인 실패 " + errorCode);
이 부분 수정했습니다 :)

2021-07-29 15:21 UTC, xlffm3 commented
![image](https://user-images.githubusercontent.com/56240505/127499845-cec1bc57-5339-431c-8171-8236f606198e.png)

![image](https://user-images.githubusercontent.com/56240505/127499910-36fb5b0d-f0d5-472e-8b76-13f3fc9cb664.png)

* 상단은 db, error 등의 logger이며 하단은 access-logger의 모습입니다.
  * db 관련 로그 : logs/db.log
  * error 관련 로그 : logs/error.log
  * access 관련 로그 : logs/access.log
  * 로 남도록 변경했습니다.
     * 현재 우리 어플리케이션 예외 + 스프링 예외를 INFO 이상 찍고 있기 때문에 **에러가 아닌 부분**들도 에러 로그에 일부 포함되지만, 개의치않는 수준이라 에러 로그로 퉁쳐놨습니다.
     * 추후 info log와 error log를 분리할 필요가 있다면 그럴 계획입니다.
* 상단 로거 관련 설정의 root는 logback-spring.xml이며, access-logger 관련 설정의 root는 logback-access.xml 입니다.
* ActiveProfile이 test로 설정되어있지 않은 테스트 클래스는 로거 기능을 사용할 수 없습니다.
* 현재는 prod와 local 모두 logs 디렉토리에 쌓이도록 했습니다.
   * 프로필별 디렉토리를 기존에는 logs/prod, logs/local로 구분했었는데, 배포 서버에서 local로, 개발 서버에서 prod로 돌릴 일이 없다고 판단하여 통합했습니다.
   * 추후 필요하다면 프로필별로 디렉토리를 분리할 예정입니다. 
* 기존에는 prod는 dml을 제외한 쿼리 관련 로그를 남기지 않는다고 했는데, prod 또한 로그를 남기는게 낫다고 판단되어 추가해두었습니다.
   * 만약 추후 성능 이슈가 있다면 제거해도 좋을 것 같습니다.

2021-07-30 08:02 UTC, da-nyee approved these changes
케빈 수고하셨습니다 👏

정리해둔 코멘트 잘 읽었습니다!
어제 논의한 대로 잘 반영해주셨네요 👍👍

2021-07-30 09:11 UTC, merged