[#222] 프로필 페이지 피드 버그 수정
woowacourse-teams/2021-pick-git pull request #242
Opened 2021-07-22 17:34 UTC by Tanney-102

## 상세 내용
- 프로필 피드가 5개만 나오는 버그 수정(무한 스크롤 추가)
- 프로필 레이아웃 버그 수정
- 프로필 페이지 관련 모든 상태로직을 훅으로 분리
- 훅으로 분리된 상태와 상태로직들을 context로 한번 더 분리

프로필 페이지 하위의 컴포넌트에서 훅을 사용하다보니 다음과 같은 문제를 마주하게 되었습니다.
1. 옵셔널하게 렌더링 되는 컴포넌트 안에서 훅이 사용되는 문제
2. 공통으로 사용되는 상태에 대한 prop drilling

이에 프로필 페이지 바로 상단을 context로 감싸 상태를 공유하도록 했습니다.
리팩터링을 하면서 각 페이지의 상태를 각각 관리하는 아키텍처를 도입해보면 어떨까 싶습니다!
context를 사용해도 되지만 추후에는 예측 가능한 상태관리 라이브러리를 사용해도 좋을 것 같습니다.

<br/>

Close #222

2021-07-22 18:04 UTC, swon3210 requested changes
어플리케이션 기능이 많아지고 구조가 복잡해짐에 따라 전역 상태들이 점점 많아지는 것 같습니다. 상태 관리 라이브러리를 도입하고, 설계를 어떻게 할지를 확실히 이야기해볼 필요가 있을 것 같습니다.

2021-07-22 18:04 UTC, swon3210 commented on frontend/src/services/hooks/useProfile.ts
> +  const { pushSnackbarMessage } = useContext(SnackBarContext);
다른 상태 관리 라이브러리를 도입하더라도 전역상태 -> 훅에서 가져와서 사용 or 전역 상태 <- 훅을 가져와서 사용 중 하나의 일관된 흐름을 가져야 할 것이라고 생각합니다.

2021-07-22 18:04 UTC, swon3210 commented on frontend/src/components/GithubStatistics/GithubStatistics.tsx
> +      </div>
PageLoading 컴포넌트를 div 로 감싸주지 않으면 발생하는 레이아웃 에러가 혹시 있나요? 있으면 바로 고치도록 하겠습니다.

2021-07-22 18:29 UTC, Tanney-102 commented on frontend/src/contexts/ProfileContext.tsx
> +  const profileProps = useProfile(isMyProfile, fixedUsername);
context와 hook은 사용목적 자체가 다르다고 생각합니다
context는 지역적인 store를 형성하기 위한 목적이고 hook은 상태로직과 사이드 이펙트를 포함하는 서비스 부분을 담당시킬 목적으로 사용했습니다. 저는 오히려 가지고 있는 상태가 많아 컨텍스트를 도메인 별로 나눠 사용하는 것보다 각 도메인에 해당하는 서비스 로직을 훅으로 분리해 하나의 스토어에서 내려주는 방식이 좋은 아키텍처라는 생각이 드네요!

2021-07-22 18:30 UTC, Tanney-102 commented on frontend/src/components/ProfileFeed/ProfileFeed.tsx
> +  const { allPosts, isLoading, isError, isFetchingNextPage, handleIntersect } = userFeedProps ?? {};
profile context value의 초기 값을 특정하기 어려워 우선 null을 넣어놓았습니다. 추후 상태관리 라이브러리를 도입하거나 혹은 다른 방법을 고민해봐야할 것 같네요

2021-07-22 18:33 UTC, Tanney-102 commented on frontend/src/services/hooks/useProfile.ts
> +  const { pushSnackbarMessage } = useContext(SnackBarContext);
ProfileContext는 전역상태라기 보단 Profile 페이지에 해당하는 지역 context라고 보는게 적절하지 않을까요?
context에 계층이 나뉘는게 어색하진 않다고 생각이 들고 데이터 흐름의 예측이 어려운 것은 reducer와 action을 정의하지 않은 상태의 context가 가지는 문제이지 지금의 아키텍처만의 문제는 아니라고 생각합니다.

2021-07-22 18:35 UTC, Tanney-102 commented on frontend/src/components/GithubStatistics/GithubStatistics.tsx
> +      </div>
아 컨테이너가 따로 있는걸 생각못했네요 ㅎㅎ 수정했습니다!

2021-07-22 18:48 UTC, Tanney-102 commented on frontend/src/contexts/ProfileContext.tsx
> +  const profileProps = useProfile(isMyProfile, fixedUsername);
그리고 context안에서 커스텀 훅을 사용하는게 어색하다면 context에서 상태를 사용하기 위해 useState라는 훅을 사용하는 것도 어색해야하지 않을까 하는 생각이 듭니다! 결국 원하는 스코프 내에서 공유하는 "상태"를 가지고 있는 것이 context이고 그 안에서 커스텀 훅을 사용하는 것은 자기 상태를 갖는 컴포넌트 안에서 커스텀 훅을 사용하는 것과 같은 이유를 갖는다고 생각하면 어떨까요?

2021-07-23 01:29 UTC, swon3210 commented on frontend/src/services/hooks/useProfile.ts
> +  const { pushSnackbarMessage } = useContext(SnackBarContext);
아하 컨텍스트 간의 계층 관계를 만들고 이를 훅을 통해 연결 지으려고 했던 것이군요. 지금은 의도가 잘 이해됩니다. context 와 hook 의 사용 목적 또한 분명하게 구분해주셨다고 생각합니다. context를 지역적으로 사용할 수 있다는 점은 제가 놓친 부분이네요. 제가 말한 '혼란'에 대한 부분도 더 자세히 밝혔어야 했다고 생각합니다.

import 코드의 횟수를 줄이고, 언뜻 의미 없어 보이는 useHook, useContext 의 실행 횟수를 줄일 수 있다는 점에서도 이 방법이 나쁘지 않게 생각됩니다.

다만 저는 상태로직과 사이드 이펙트를 지닌 훅을 context 가 자체적으로 지니게 되면서 해당 context 가 단순 지역 store 이상의 기능을 떠맡게 되는 것을 경계해야 한다고 생각합니다. 그 이유는 작성해주신 Profile Context 의 예를 들어 설명해보겠습니다.

![image](https://user-images.githubusercontent.com/32982670/126725577-2ed142c2-ef02-430c-9da9-bb24ce58a363.png)

context 내부에 훅을 실행하게 되면서 ProfileContext 는 단순히 불러오는 것 만으로 불러온 훅 안의 내용이 실행되는 결과를 낳게 됩니다. 사용되는 useUserFeed 훅의 경우에는 useEffect 구문이 두 개 정도 있는데, ProfileContext를 사용하는 쪽에서는 이 둘의 동작을 예측하기 훨씬 어려우리라 생각합니다.

훅을 실행하게 되면서 생겨나는 'context 내부에서 외부 상태 변경 로직을 실행할 수 있는 가능성' 또한 무시할 수 없으리라 생각합니다. 물론 현재는 useUserFeed 등 다른 훅으로 불러오는 객체들을 전달하는 용도 정도로만 쓰이고 있고 설마 그런 일을 할까 싶기는 하겠지만 저는 그러한 가능성 자체를 원천 차단하는 것이 바람직하다고 생각합니다. (제가 '그런 일'을 무심코 몇 번 해본 기억이 있어서...)

reducer와 action 이 없어서 데이터 흐름을 예측하기 어려운 것은 맞지만 저는 context 와 훅이 사용되는 총 단계를 조금 낮추는 것으로 데이터 흐름 예측 가능성을 조금이라도 더 높일 수 있으리라 생각됩니다. 

![image](https://user-images.githubusercontent.com/32982670/126727773-d0556861-8250-4803-9aeb-4984354bbd68.png)

![image](https://user-images.githubusercontent.com/32982670/126727787-c545efc0-d016-41d9-81ed-80f144010325.png)


* p.s : context 에서 useState 와 같은 훅을 쓸 수 있는 이유는 해당 훅이 어떤 사이드 이펙트를 일으킬 수 있는 가능성이 거의 없기 때문이라고 생각합니다. 하지만 개발자가 직접 작성하게 되는 커스텀 훅은 추후에 어떤 사이드 이펙트를 지니게 될지 모르기 때문에, 저는 사용을 context 내부에서 커스텀 훅을 사용하는 것을 자제하는게 맞다고 생각합니다.

2021-07-23 03:17 UTC, Tanney-102 commented
합의한 내용대로 컨텍스트를 제거하고 필요한 부분에 컴포넌트를 하나 추가했습니다

현재
```
ProfilePage
  ├ Profile
  │    ├ ProfileHeader
  ├ Tabs
  ├ ProfileTabContents
       ├ ProfileFeed
       ├ GithubStatistics
```
이런 컴포넌트 구조를 가지고 있습니다.
이렇게 놓고보니 깔끔하게 해결된 것 같네요 ㅎㅎ

2021-07-23 03:21 UTC, swon3210 approved these changes
와 빨리 수정해주셨네요...! 감사합니다.

수고하셨습니다!

2021-07-23 03:26 UTC, merged