[#234] 태그 테스트 코드를 리팩토링
woowacourse-teams/2021-pick-git pull request #245
Opened 2021-07-23 07:31 UTC by binghe819

# 태그

<br>

## 프로덕션 수정사항

* `GithubPlatformTagApiRequester`
  * 테스트에선 `MockTagApiRequester`만들어 사용해서, 예상한대로 `PlatformHttpErrorException`가 발생하도록 함.
  * 하지만 실제 프로덕션 코드에선 `HttpClientErrorException`가 발생함. 그래서 try-catch로 감싸서 `PlatformHttpErrorException`를 던지도록 수정함.
* PostTag - Tag 와의 영속성 전이 수정으로 인한 프로덕션 코드 수정.
* connection pool사용하는 `RestTemplate`로 수정함.
* 빌더 패턴 적용.

<br>

## 단위 테스트

<br>

### Domain, Infrastructure

* `Tag`
  * 성공 - 정상 생성 테스트 (`new`)
  * 실패 - 태그 이름이 null이거나 빈 문자열이거나 20자를 넘어가면 예외가 발생한다. (`new`)
  * 기타 - 동등성 테스트 (`equals`)
* `TagRepository`
  * 성공 - 태그를 저장하고 찾을 수 있다. (`findByName`)
  * 실패 - 존재하지 않는 태그 조회시 Optional.empty를 반환한다. (`findByName`)
  * 실패 - 이미 존재하는 태그(이름)을 저장하면 예외가 발생한다. (`save`)
* `PlatformTagApiRequester` (`GithubTagApiRequester`)
  * 실패 - 유효하지 않은 토큰이면 예외가 발생한다. (`requestTags`)
  * 실패 - 유효한 토큰이지만 유효하지 않은 URL이면 예외가 발생한다. (`requestTags`) (ignore)
    * 유효한 토큰을 만들 방법이 떠오르지 않아 일단 제외시킴.
    * 개인적으로 토큰 발급하여 테스트해보니 `HttpClientErrorException` (404) 발생함.
* `PlatformTagExtractor` (`GithubTagExtractor`)
  * 성공 - 명시된 User의 Repository에 기술된 Language Tags를 추출한다. (`extractTags`)
  * 실패 - 토큰이 유효하지 않은 경우 권한 예외가 발생한다. (`extractTags`)
  * 실패 - 요청 URL 링크(username/repositoryname)에 해당하는 경로가 존재하지 않으면 조회 예외가 발생한다. (`extractTags`)
* `Post`
  * 성공 - Tag를 정상적으로 Post에 등록한다. (`addTags`)
  * 실패 - 중복되는 이름의 Tag가 존재하면 Post에 추가할 수 없다. (`addTags`)

<br>

### Slice

* `TagController`
  * 성공 - 특정 User의 Repository에 기술된 언어 태그들을 추출한다.
  * 실패 - 유효하지 않은 AccessToken으로 태그 추출 요청시 401 예외 메시지가 반환된다.
  * 실패 - 유효하지 않은 레포지토리 태그 추출 요청시 404 예외 메시지가 반환된다.
* `TagService`
  * 성공 - Repository에 포함된 언어 태그를 추출한다.
  * 성공 - 태그 이름을 태그로 변환한다.
  * 실패 - 잘못된 경로로 태그 추출 요청시 예외가 발생한다.
  * 실패 - 유효하지 않은 토큰으로 태그 추출 요청시 예외가 발생한다.
  * 실패 - 잘못된 태그 이름을 태그로 변환 시도시 실패한다.
  * 기타 - 태그 이름이 없다면 빈 태그를 반환한다.

<br>

## 통합 테스트

* `TagService`
  * 성공 - Repository에 포함된 언어 태그를 추출한다.
  * 성공 - 태그 이름을 태그로 변환한다.
  * 실패 - 잘못된 경로로 태그 추출 요청시 예외가 발생한다.
  * 실패 - 유효하지 않은 토큰으로 태그 추출 요청시 예외가 발생한다.
  * 실패 - 잘못된 태그 이름을 태그로 변환 시도시 실패한다.

<br>

## 인수 테스트

* `TagAcceptance`
  * 성공 - 특정 User의 Repository에 기술된 언어 태그들을 추출한다.
  * 실패 - 유효하지 않은 레포지토리 태그 추출 요청시 500 예외 메시지가 반환된다.
  * 실패 - 유효하지 않은 AccessToken으로 태그 추출 요청시 서버 에러가 발생한다.
  * 실패 - 토큰을 포함하지 않고 태그 추출 요청시 401예외가 발생한다.
* `PostAcceptance`
  * 성공 - 사용자는 태그가 없이도 게시글을 작성할 수 있다.
  * 실패 - 사용자는 중복된 태그를 가진 게시글을 작성할 수 없다.

<br>

## 고민거리

* Github API에 RestTemplate로 요청할 때 크게 두 가지 예외가 발생한다. (두 가지 모두 `HttpClientErrorException`를 던진다.)
  * 처리 방식 1: GithubTagApiRequester에서 try-catch하여 `PlatformHttpErrorException` 을 던지는 방식
  * 처리 방식 2: GithubTagApiRequester에선 try-catch하지 않고, `GlobalExceptionHandler`에서 `HttpClientErrorException`를 잡아서 처리하는 방법
  * 일단은 기존의 예외처리 전략을 활용하고자 처리 방식 1로 리팩토링 함.
* 다대다 관계에서 `cascade` 의 범위는 어디까지 하는 것이 좋은가? -> 해결
  * 게시물과 태그는 N : N 관계다. 물론 구현상에선 중간 테이블을 엔티티로 격상해서 사용한다.
  * 하지만, 통상적으로 권장하는 cascade 범위는 완전히 개인 소유하는 엔티티일 때만 이라고 한다.
  * 그렇다면 PostTag - Post의 관계는 cascade이되, PostTag - Tag는 cascade 옵션을 하지 않는 것이 좋은 설계이지 않나 생각든다.
  * https://www.inflearn.com/questions/37062
* 게시물 작성시 태그가 없으면 어떻게 할 것인지?
  * 성공 or 실패?
  * 일단 성공한다는 가정하에 프로덕션 코드와 테스트 코드를 작성함.
* 더 많은 엣지 케이스를 생각해야할 듯 합니다. 하지만.. 떠오르지 않네요.. 

Close #234

2021-07-23 08:41 UTC, xlffm3 approved these changes
안녕하세요 마크~ 태그 부분 수정하느라 고생많으셨습니다.
앞으로 추가 요구사항이 생겨날수록 태그 관련 테스트도 더 많아질텐데요.

몇 가지 의견 남겼으니 참고하셔서 반영해주시면 감사하겠습니다 :)

2021-07-23 08:41 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/infrastructure/GithubTagApiRequester.java
> +        }
네 저는 마크가 리팩토링한 방식이 괜찮다고 생각해요.
현재 develop 브랜치에는 반영되지 않았지만, 추후 우리가 만든 커스텀 예외가 아닌 예외들에 대해서는 RuntimeException 등으로 핸들링할 것같은데요.

HttpClientErrorException에 대해 별도의 어드바이저를 등록해두지 않으면 RuntimeException 핸들러가 동작해서 500 에러와 에러 메시지를 반환할텐데요.

그것보다는 위 코드처럼 우리가 사용하는 커스텀 예외로 변환해주는게 프론트와 백 모두 예외 상황을 잘 이해하는데 도움이 될 것 같습니다.

아울러 만약 RestTemplate이 아니라 WebClient나 다른 구현체를 사용한다면, ApiRequester뿐만 아니라 HttpClientErrorException을 핸들링하는 어드바이저 또한 변경되어야 하니...!

2021-07-23 08:41 UTC, xlffm3 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/tag/TagAcceptanceTest.java
>      @DisplayName("특정 User의 Repository에 기술된 언어 태그들을 추출한다.")
Tag 인수테스트 43번째 줄에 사용하지 않는 변수가 존재하네용

2021-07-23 08:41 UTC, xlffm3 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest.java
> +    void save_WhenSavingPostAndNotExistsTag_PostTagSavedTogether() {
바로 위의 ``void save_WhenSavingPostAndExistsTag_PostTagSavedTogether()`` 테스트와 내용이 동일해보이는데요.

2021-07-23 08:41 UTC, xlffm3 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/application/TagServiceTest.java
>      void findOrCreateTags_InvalidTagName_ExceptionThrown() {
만약 도메인 검증을 더 철저하게 하고자 한다면 @ParameterizedTest로 NullAndEmptySource, 20자 이상을 줘도 될 것 같네요. 개인적인 의견입니다!

2021-07-23 08:41 UTC, xlffm3 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/infrastructure/GithubTagApiRequesterTest.java
> +    void requestTags_InvalidAccessToken_ExceptionThrown() {
음, 실제로 테스트를 위해 api를 요청하는데 이 부분에 대해서 어떻게 생각하세요?

저는 실제 API 요청을 날리는 부분 때문에 Extractor를 테스트하기 어려워서, Resttemplate을 사용하는 부분을 ApiRequester라는 인터페이스로 추출한 다음 테스트에서는 Common 패키지에 위치한 MockRequester를 사용하도록 했는데요.

경로가 잘못되거나 액세스토큰이 이상한 경우 Github API가 예외를 터트린다고 신뢰 및 가정하는게 낫지 않을까 싶어서요!

2021-07-24 09:39 UTC, binghe819 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/infrastructure/GithubTagApiRequester.java
> +        }
공감되는 답변이네요 👍

2021-07-24 09:41 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest.java
> +    void save_WhenSavingPostAndNotExistsTag_PostTagSavedTogether() {
그렇네요! 👍

2021-07-24 09:51 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/application/TagServiceTest.java
>      void findOrCreateTags_InvalidTagName_ExceptionThrown() {
오! 수정하는게 좋을 듯 합니다! 👍 수정해서 push 할게요~

2021-07-24 10:05 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/infrastructure/GithubTagApiRequesterTest.java
> +    void requestTags_InvalidAccessToken_ExceptionThrown() {
넵넵! 저도 케빈 의견처럼 `MockRequester`를 통해 Github API가 예외를 터트린다고 신뢰 및 가정하고 테스트 하는 것이 맞다고 생각듭니다.

다만, 위 코드를 작성한 이유는 테스트 코드가 문서화의 역할도 한다는 생각이어서 작성하게 되었습니다!

즉, 실제 Github API에 요청을 날리면 어떤 예외가 터지는지 알리기 위함이었습니다!

2021-07-24 10:08 UTC, binghe819 commented
@xlffm3  피드백 적용했습니다 :)

2021-07-25 08:59 UTC, yjksw approved these changes
마크!! 꼼꼼한 테스트 잘 작성하셨네요 ㅎㅎ 
수고하셨습니다~~~👍

2021-07-25 08:59 UTC, yjksw commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +    }
이미 프론트에서도 대소문자 관련을 처리해주긴 하지만 백엔드에서도 처리하는 건 어떨까요? 물론 선택사항입니다~

2021-07-25 08:59 UTC, yjksw commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/application/TagService.java
> +                );
굳 깔끔하고 좋네요!

2021-07-25 08:59 UTC, yjksw commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
> +    @DisplayName("")
엇 Display Name이 공백이네요!

2021-07-25 09:35 UTC, da-nyee requested changes
마크 수고하셨습니다 👏

코드 리뷰 확인해주세요!
피드백 반영되면 Approve 하겠습니다 !

2021-07-25 09:35 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/tag/TagAcceptanceTest.java
>          when(oAuthClient.getAccessToken(oauthCode)).thenReturn(accessToken);
```suggestion
        given(oAuthClient.getAccessToken(oauthCode)).willReturn(accessToken);
```

given()을 사용하도록 변경해주세요!

2021-07-25 09:35 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
> +            .isInstanceOf(CannotAddTagException.class);
```suggestion
        assertThatCode(() -> postService.write(requestDto))
            .isInstanceOf(CannotAddTagException.class)
            .hasFieldOrPropertyWithValue("errorCode", "XXX")
            .hasFieldOrPropertyWithValue("httpStatus", "XXX")
            .hasMessage("XXX");
```

이렇게 발생하는 예외의 에러 코드, 상태 코드, 메시지까지 확인할 수 있어요 !

2021-07-25 09:35 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/tag/TagServiceIntegrationTest.java
>              .extracting("errorCode")
이 예외 케이스에서 특수 문자가 들어가는 경우도 테스트해주세요!

2021-07-25 09:35 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/tag/TagServiceIntegrationTest.java
>              .extracting("errorCode")
DTO에 `@Pattern(regex="XXX")`를 추가해야 할 거 같은데, PostRequest에 태그가 List로 들어있어서 애매하네요,,
커스텀 Validator를 생성해서 검증해야 할까요?

2021-07-25 09:35 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest.java
> +        assertThat(findPost).isNotNull();
```suggestion
        assertThat(findPost.getId()).isNotNull();
```

객체가 null이 아닌지 검증하는 것보다 객체 id가 null이 아닌지 검증하는 게 더 낫지 않을까요?

2021-07-25 09:35 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/domain/TagTest.java
> +    @ValueSource(strings = {"abcdeabcdeabcdeabcdea", " ", "  "})
특수문자(하이픈, 언더바 제외)도 확인해주세요!

2021-07-25 09:35 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/infrastructure/GithubTagApiRequesterTest.java
> +    void requestTags_InvalidAccessToken_ExceptionThrown() {
실제로 Github API에 요청을 보내는 거면, 이 테스트는 단위 테스트가 아니라 통합 테스트여야 하지 않을까요?
여기서는 케빈 방식대로 MockRequester를 사용하고 통합에서 마크 방식대로 ApiRequester를 사용하는 게 맞을 것 같습니다.

2021-07-25 18:10 UTC, binghe819 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +    }
오! 대소문자 같은 것으로 보나요??

2021-07-25 18:11 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
> +    @DisplayName("")
아이고.. 내 정신이야

2021-07-25 18:16 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
> +    @DisplayName("")
아이고.. 저런..

2021-07-25 18:18 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/tag/TagAcceptanceTest.java
>          when(oAuthClient.getAccessToken(oauthCode)).thenReturn(accessToken);
아이고..ㅋㅋㅋ 주의 하겠습니다!

2021-07-25 18:24 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
> +            .extract();
저도 처음엔 이렇게 작성했지만, 게시물 작성후 리다이렉션이 걸려서 부득이하게 위와 같이 작성하게 되었습니다ㅠ

2021-07-25 23:43 UTC, bperhaps approved these changes
좋네요.... 소소한 코멘트 조금 남겼어요... 수고하셨습니다!

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
>      }
이 행위를 Post에서 담당하는게 맞을까요? 저는 PostTags 객체로 책임을 넘겨야 한다고 생각합니다.

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +    }
부분도 마찬가지로 postTags로 책임이 넘어가겠네요

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
>      public List<Tag> getTags() {
getTags의 로직도 postTags로 옮겨야 겠군요

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostTag.java
>      private Post post;
NonNull은 lombok어노테이션 입니다. 도메인과 롬복의 의존성을 만드는건 지양하는게 좋기 때문에 null 확인 로직을 생성해 주던가, 생성자 주입만을 허용시켜 강제로 null이 아니게 만들어 주는 편이 좋아보입니다.

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/application/TagService.java
>          }
```
tagsDto.getTagNames().forEach(
            tagName -> tagRepository.findByName(tagName)
                .ifPresentOrElse(tags::add, () -> tags.add(tagRepository.save(new Tag(tagName))))
        );
```

이런식의 리팩토링은 어떤가요?

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/tag/TagServiceIntegrationTest.java
>              .extracting("errorCode")
https://www.baeldung.com/spring-validate-list-controller

벨덩은 모르는게 없는듯.

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/tag/TagServiceIntegrationTest.java
>              .extracting("errorCode")
갠적으로는 커스텀 validation 그지같은데, 컨트롤러 validation도 그지같아서...... 둘중 고르라면 그래도 난 후자..

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest.java
> +    @DisplayName("Post를 저장할 때 Tag는 함께 영속화되지 않는다. (태그가 존재하지 않을 경우 예외가 발생한다)")
아 이 파일 나도 수정했는데 충돌나것네..

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest.java
> +        assertThat(findPost).isNotNull();
@da-nyee 객체 자체가 db에 존재하는지 확인하는 로직이라 원래가 맞는덧

2021-07-25 23:43 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/application/TagServiceTest.java
> +        assertThat(tags.size()).isEqualTo(0);
```suggestion
        assertThat(tags.size()).isZero()
```

2021-07-26 03:52 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostTag.java
>      private Post post;
@bperhaps 헉 롬복 어노테이션인 줄 몰랐네요. null 확인 로직을 따로 생성하는 게 나을 거 같습니다!

2021-07-26 06:46 UTC, da-nyee requested changes
마크 빠른 피드백 반영 좋습니다 👍

코멘트 몇 개 더 남겼는데 확인해주세요!

2021-07-26 06:46 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/application/TagService.java
> +            .map(String::toLowerCase)
소문자 매핑 좋아요 👍

2021-07-26 06:46 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/domain/Tag.java
> +        this.name = name.toLowerCase();
생성자에 소문자 변환 로직이 들어가는 게 맞을까요??

2021-07-26 06:46 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/tag/TagServiceIntegrationTest.java
> +        assertThat(tagsDto.getTagNames()).containsAll(Arrays.asList("javascript", "html", "css"));
Arrays.asList() 대신 List.of() 사용할 수 있을 거 같아요!

2021-07-26 09:04 UTC, da-nyee approved these changes
마크 수고하셨습니다 👏👏

2021-07-27 00:22 UTC, merged