[#269] 게시물 수정 및 삭제 기능 구현
woowacourse-teams/2021-pick-git pull request #272
Opened 2021-07-28 16:29 UTC by da-nyee

## 상세 내용
### 슬라이스 테스트 - 컨트롤러
#### update
- 사용자는 게시물을 수정한다.
- 유효하지 않은 내용(null)으로 게시물을 수정할 수 없다. - 400 예외
- 유효하지 않은 내용(500자 초)으로 게시물을 수정할 수 없다. - 400 예외

#### delete
- 사용자는 게시물을 삭제한다.

<br/>

### 슬라이스 테스트 - 서비스
#### update
- 사용자는 게시물의 내용을 수정한다.
- 게스트는 게시물의 내용을 수정할 수 없다.
- 등록되지 않은 게시물의 내용을 수정할 수 없다. - 500 예외

#### delete
- 사용자는 게시물을 삭제한다.
- 게스트는 게시물을 삭제할 수 없다. - 401 예외
- 등록되지 않은 게시물을 삭제할 수 없다. - 500 예외

<br/>

### 통합 테스트
#### update
- 사용자는 게시물의 태그, 내용을 수정한다.
- 사용자는 게시물의 태그를 수정한다.
- 사용자는 게시물의 내용을 수정한다.
- 게스트는 게시물을 수정할 수 없다. - 401 예외
- 등록되지 않은 게시물을 수정할 수 없다. - 500 예외

#### delete
- 사용자는 게시물을 삭제한다.
- 게스트는 게시물을 삭제할 수 없다. - 401 예외
- 등록되지 않은 게시물은 삭제할 수 없다. - 500 예외

<br/>

###  인수 테스트
#### update
- 사용자는 게시물을 수정한다.
- 유효하지 않은 내용(null)의 게시물은 수정할 수 없다. - 400 예외
- 유효하지 않은 내용(500자 초과)의 게시물은 수정할 수 없다. - 400 예외
- 유효하지 않은 토큰으로 게시물을 수정할 수 없다. - 401 예외

#### delete
- 사용자는 게시물을 삭제한다.
- 유효하지 않은 토큰으로 게시물을 삭제할 수 없다. - 401 예외

<br/>

Close #269

2021-07-29 02:25 UTC, xlffm3 reviewed
안녕하세요 다니.
게시물 수정 및 삭제 기능 구현하느라 고생많으셨습니다.
인수 테스트가 꼼꼼하게 잘 작성되어있어서 인상깊었습니다 :)

다만 일부 도메인 로직의 테스트가 빠져있는데요.

1. Post.update 도메인 단위 테스트
2. PostRepository 테스트
    * 게시물 삭제할 때 관련되어 있는 엔티티들이 잘 삭제되는가?
    * 게시물을 삭제할 때 태그 처리 (이 부분은 논의가 필요하겠네요. 다른 게시물이 동일한 태그를 참조할 때는 삭제하면 안 되는데, 특정 태그를 참조하는 게시물이 하나도 존재하지 않는다면 지워져야하니)
3. PostAcceptance & Controller 슬라이싱 테스트
   * 게스트일 때 수정 및 삭제 시도 테스트

일정 봐서 테스트를 전부 추가하지 못한다면 일단 머지후 리팩토링해도될것같습니다!

2021-07-29 02:25 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +
Tag 추가 삭제만 하는데도 Post에 너무 많은 코드(태그 중복 여부나 태그를 추가할 수 있는지 등의 책임
)가 존재하는것을 보니
슬슬 ``List<PostTag>``를 임베디드 타입으로 분리할 시기가 됐나보네요.

* 아, 이미 너잘이 리팩토링하면서 분리해두었네요.

2021-07-29 02:25 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +    public Post update(String content, List<Tag> tags) {
이건 추가 기능과도 일맥상통하는데 태그 개수 제한도 필요해보입니다.

2021-07-29 02:25 UTC, xlffm3 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
> +    void update_GuestUser_401Exception() {
AppUser 로직때문에 애매하네요. 게스트 관련 테스트들은 꼭 통합테스트가 아니라 DTO 단위 테스트로도 충분해보입니다.

2021-07-29 02:25 UTC, xlffm3 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
> +            .findById(anyLong());
특정할 수 있는 값이라면 any 대신 값을 넣어주세요.
추후 테스트 내용이 변경되더라도 any로 인해 문제를 파악하기 어려운 경우가 있습니다.

2021-07-29 09:11 UTC, bperhaps reviewed
다니 수고하셨습니다!

2021-07-29 09:11 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +    public Post update(String content, List<Tag> tags) {
post entity에 update라는 메서드가 있는게 어색하다고 느껴져요.
update에 있는 로직은 service에 위치하는게 더 올바른 것 같습니다...!

2021-07-29 09:11 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
> +    @DisplayName("사용자는 게시물을 수정한다.")
요청자의 게시물이 맞는지 확인하는 테스트가 필요해 보입니다!

2021-07-29 09:11 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
> +    @DisplayName("사용자는 게시물을 삭제한다.")
요청자의 게시물이 맞는지 확인하는 테스트가 필요해 보입니다!

2021-07-30 09:40 UTC, yjksw requested changes
안녕하세요 다니~~! 꼼꼼한 코드 잘 봤습니다 ㅎㅎㅎ 
태그 관련 전체 삭제 후 추가가 어제 말한 애매한 상황이군요 ㅠㅠㅠ 
아무래도 다같이 고민을 해보면 좋을 것 같아요 !! 
그리고 현재 유저가 본인이 작성한 글이 아니라도 수정 및 삭제를 할 수 있는 것 같아요!
그 부분에 대한 프로덕션 로직 추가 및 테스트가 추가되면 좋을 것 같습니다 ~!

2021-07-30 09:40 UTC, yjksw commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
> +            .findById(anyLong());
굳 특정하는 값을 넣으니까 걸러지는 케이스가 있더라구요!!

2021-07-30 09:40 UTC, yjksw commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
> +    @DisplayName("사용자는 게시물을 삭제한다.")
현재 요청하는 유저의 게시물인지 확인하는 로직이 없는 것 같아요 !

2021-07-30 09:42 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +    public Post update(String content, List<Tag> tags) {
이 부분은 추후에 PostTags 임베디드 타입으로 옮겨야 할 것 같습니다!

2021-07-30 10:14 UTC, bperhaps approved these changes
안녕하세요 다니 리팩토링한 코드 잘 읽었습니다 :)
코멘트 하나 남겼는데 한번 생각해 보시면 좋을 것 같아요! "객체"란 무엇일까요? Entity는 무엇을 의미하는걸까요? 개발자는 사실 철학적 관점으로 기술을 바라봐야하는 직업이라고 생각해요 (DDD가 어렵다고 말하는 이유도 이거에요, 에릭 에반슨의 DDD를 읽어보면 기술에 대해서 말하지 않아요. 철학에 대해서만 말해요, 엔티티란 무엇인가.. 유비쿼터스... 등등...) 따라서 기술의 구현뿐만 아니라 각 코드의 의미도 생각하면 더 좋을거라고 생각합니다!

수고하셨습니다!

2021-07-30 10:14 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
> +            .update(createPostUpdateRequestDto(user, postId, updateRequest));
추상화 수준에 대해서 바로 적용 대단합니다👍

2021-07-30 10:14 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
> +    }
저번 리뷰에서도 말했지만, Post라는 Entity가 update라는 메서드를 가지고 있는게 어색하다고 느껴집니다 :)
Post가 post 그 자체를 의미한다고 생각하면, 그리고 그 상태를 관리하는 주체라고 생각한다면 
updateContent() or changeContent()
update Tags() or changeTags()
와 같은 메서드를 가지고 자신의 상태를 각자 관리할 수 있도록 만들어 줘야 한다고 생각합니다.
그리고 서비스쪽에서는 저 메서드를 통해 service에서 그 흐름을 제어할 수 있어야 하구요.
현재는 흐름제어가 도메인으로 침투했다는 느낌을 강하게 지울수가 없어요.
addTags를 재활용 하고 싶다면, addTags의 이름 자체를 updateTags와 같이 변경하고 메서드의 상단에 clear 로직을 두는것으로 어느정도 해결해 보입니다. 그렇다면 코드의 문맥상으로도 어느 로직에서나 자연스럽구요 :)

2021-07-30 10:14 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostTag.java
> +    }
디미터의 법칙 준수 멋집니다!

2021-07-30 14:14 UTC, yjksw approved these changes

2021-07-30 14:36 UTC, merged