[#340] 프로필 이미지 수정/정보 수정 API 기능 분리
woowacourse-teams/2021-pick-git pull request #352
Opened 2021-08-05 06:36 UTC by binghe819

## 상세 내용
- 기존 프로필 수정
  - 멀티파트를 이용하여 이미지 + 내용(한 줄 소개)를 한번에 수정. (POST)
- 변경후 프로필 수정 (API 분리)
  - Body에 이미지 바이트 배열 보내서 수정. (PUT)
  - 내용(한 줄 소개) 수정. (PUT)

<br>

이미지 변경시 아래와 같이 바디에 바이트 배열을 보내서 수정하는 방식입니다.

<img width="970" alt="스크린샷 2021-08-05 오후 3 18 18" src="https://user-images.githubusercontent.com/56860124/128302811-94d5ad05-077a-4593-89de-84581c300c4a.png">

<br>

## 기타
- 바이트 배열을 그대로 받는 것이라서 이미지 수정 부분 restdocs를 어떻게 작성해야 할지 모르겠네요... 더 찾아보고 방법이 있으면 적용해보겠습니다!

<br/>

Close #340

2021-08-05 19:22 UTC, bperhaps reviewed
수고하셨어요 마크. 업로드 부분 많이 힘들었을 텐데 잘 해 주셨네요!
코멘트 간단히 몇개 남겼습니다.

2021-08-05 19:22 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/UserService.java
> +    public ProfileImageEditResponseDto editProfileImage(
```suggestion
    public ProfileImageEditResponseDto editProfileImage (
```

2021-08-05 19:22 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/UserService.java
> +
관련 메서드들이 service에 존재하는건 책임이 적절하지 않은 것 같아요.
해당 책임을 S3Storage 클래스에 몰아 넣어 주세요. interface도 알맞게 추가해 주시면 될 것 같아요.

2021-08-05 19:22 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptanceTest.java
> +            .as(ProfileImageEditResponse.class);
빌더에 버그가 있네 미안 ㅎ

2021-08-06 08:33 UTC, xlffm3 approved these changes
마크 구현하느라 고생많으셨어요.
너잘이 말한대로 파일업로드부분만 서비스에서 로직 없애면 충분할것같네요
나중에 이미지 업로드부분 설명해주세요 ㅎㅎ

2021-08-06 09:26 UTC, da-nyee requested changes
마크 고생하셨습니다 👏

코멘트 몇 개 남겼는데, `@Size` 반영하면 바로 Approve 할게요!
이미지 부분 나중에 설명해주세요 ~!

2021-08-06 09:26 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserController.java
> +        @RequestBody byte[] image
바디에 바이트 배열 들어오는 거 신기하네요 😮

2021-08-06 09:26 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/request/ProfileDescriptionRequest.java
> +    private String description;
```suggestion
    @NotNull
    @Size(max = 160)
    private String description;
```

한 줄 소개 길이 제한(+ 테스트) 추가해주세요!

2021-08-06 09:26 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/request/ProfileDescriptionRequest.java
> +    }
```suggestion
    public String getDescription() {
        return description;
    }
```

2021-08-06 09:26 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/application/UserServiceTest.java
> +                .store(any(File.class), anyString());
```suggestion
            assertThat(responseDto.getImageUrl()).isEqualTo(imageFile.getName());
            
            verify(userRepository, times(1))
                .findByBasicProfile_Name("testUser");
            verify(pickGitStorage, times(1))
                .store(any(File.class), anyString());
```

assertThat()이랑 verify()는 한 줄 띄워주는 게 어떤가요??

2021-08-09 09:57 UTC, da-nyee approved these changes
마크 수고하셨습니다 👍

2021-08-09 10:14 UTC, merged