[#7] StepHeader 컴포넌트 구현
woowacourse-teams/2021-pick-git pull request #47
Opened 2021-07-09 05:22 UTC by swon3210

## 상세 내용
- StepHeader 컴포넌트 구현

## 기타
- 아이콘 svg 파일 추가

2021-07-09 06:02 UTC, Tanney-102 requested changes
- a tag => Link tag
- 단위(rem, px) 컨벤션 다시 정리해봅시당!

2021-07-09 06:02 UTC, Tanney-102 commented on frontend/src/components/layout/StepHeader/StepHeader.style.ts
> +export const StepLink = styled.a`
Link!!

2021-07-09 06:02 UTC, Tanney-102 commented on frontend/src/components/layout/StepHeader/StepHeader.style.ts
> +  width: 22px;
단위 컨벤션 같이 한번 더 정리하는게 어떨까요?

2021-07-10 00:38 UTC, swon3210 commented on frontend/src/components/layout/StepHeader/StepHeader.style.ts
> +export const StepLink = styled.a`
이 부분은 좀 더 세밀한 컨트롤이 필요해서 react-router-dom 의 링크 컴포넌트가 아니라 history 객체를 이용하도록 구현했습니다.

![image](https://user-images.githubusercontent.com/32982670/125146690-23498f00-e162-11eb-8d35-6050fb266751.png)

물론 일관성을 위해서 Link 컴포넌트를 계속 쓰면 좋겠지만 이 컴포넌트에는 '뒤로가기' 기능은 따로 없는 것으로 알고 있기에 결국 history.goBack 메서드를 써야합니다. Link 컴포넌트와 history 객체를 모두 쓰기보다는 그냥 history 객체만을 쓰기를 선택했습니다. 제가 생각치 못한 부분이 더 있을까요?

2021-07-10 00:39 UTC, swon3210 commented on frontend/src/components/layout/StepHeader/StepHeader.style.ts
> +  width: 22px;
정해진 컨벤션대로 width, padding 에는 rem 단위를 쓰도록 하겠습니다!

2021-07-10 00:58 UTC, Tanney-102 approved these changes
굳굳

2021-07-10 00:59 UTC, merged