[#490] 포트폴리오 기능을 위해 필요한 공용 컴포넌트들을 구현
woowacourse-teams/2021-pick-git pull request #491
Opened 2021-09-12 18:21 UTC by swon3210

## 상세 내용

- 아이콘 파일 추가
- SVGIcon 컴포넌트를 통해 각각의 Icon 을 import 하지 않아도 icon 컴포넌트를 사용할 수 있도록 설정
- DropDown 컴포넌트 구현
- DateInput 컴포넌트 구현
- DotPaginator 컴포넌트 구현
- ToggleButton 컴포넌트 구현
- ScrollActiveHeader 컴포넌트 구현
- 커스텀 스크롤바 CSS 구현
- MediaQuery CSS 문 작성을 위한 편의 기능 추가
- 
Close #490

2021-09-12 18:21 UTC, bperhaps commented
Can one of the admins verify this patch?

2021-09-13 09:06 UTC, Tanney-102 requested changes
굳굳 고생 많으셨습니당 ㅎㅎ 근데 앞서 백엔드 커밋 머지된 부분 괜찮은 걸까요? 방학전에 비슷한 상황에서 develop 브랜치 지우고 다시 checkout 하니까 잘됐던 경험이 있어서 한 번 고려해보시면 좋을 것 같습니당! 혹시모르니까 우선 request changes 걸어놓을게요

2021-09-13 09:06 UTC, Tanney-102 commented on frontend/src/components/@layout/ScrollActiveHeader/ScrollActiveHeader.tsx
> +    // containerRef.current.onclick = toggleHeader;
아직 실험중인 기능일까요?

2021-09-13 09:06 UTC, Tanney-102 commented on frontend/src/components/@styled/scrollbar.ts
> +`;
크.. 커스텀 스크롤바 레전드..

2021-09-13 09:46 UTC, swon3210 commented on frontend/src/components/@shared/SVGIcon/SVGIcon.tsx
> +      <SVGIcon style={{ margin: "0px" }} />
저도 여러번 시도를 해본 부분이지만 뭔가 깔끔하게 하는 방법을 찾지 못해서 아직 반영은 못한 상태입니다! 후에 알아내는 대로 별도의 PR 로 올리겠습니다!

2021-09-13 09:48 UTC, swon3210 commented on frontend/src/components/@shared/ToggleButton/ToggleButton.tsx
> +      <ToggleButtonText>{toggleButtonText}</ToggleButtonText>
![image](https://user-images.githubusercontent.com/32982670/133062693-c4d85b98-9d8e-455b-b8fe-fb65c1cf0063.png)

이 컴포넌트의 경우엔 텍스트가 컴포넌트의 안쪽이나 일부로서 존재한다기 보다는 옆에 라벨로 붙는다는 느낌이어서 children 보다는 text prop 을 따로 받는게 좋겠다고 판단했습니다!

2021-09-13 09:49 UTC, swon3210 commented on frontend/src/components/@layout/ScrollActiveHeader/ScrollActiveHeader.tsx
> +    // containerRef.current.onclick = toggleHeader;
앗 지우는 걸 잊은 주석이네요! 지적 감사합니다!

2021-09-13 09:49 UTC, swon3210 commented on frontend/src/components/@styled/scrollbar.ts
> +`;
감사합니다!

2021-09-13 09:57 UTC, Tanney-102 commented on frontend/src/components/@shared/SVGIcon/SVGIcon.tsx
> +      <SVGIcon style={{ margin: "0px" }} />
```
const SVGIconWrapper = styled.div`
  ...
  svg {
    ...
  }
  ...
`
```

요렇게는 힘들까요?

2021-09-13 09:58 UTC, Tanney-102 commented on frontend/src/components/@shared/ToggleButton/ToggleButton.tsx
> +      <ToggleButtonText>{toggleButtonText}</ToggleButtonText>
오호 컴포넌트를 보니까 이해가 되네요 굳굳!

2021-09-13 10:21 UTC, swon3210 commented on frontend/src/components/@shared/SVGIcon/SVGIcon.tsx
> +      <SVGIcon style={{ margin: "0px" }} />
그게 단순히 svg 태그의 css 속성만 변경하면 되는게 아니더라구요. svg 아이콘내부의 group 태그나 다른 line 태그 등도 고유한 width 와 stroke 값 등을 가지고 있어서 svg 나 path 에 해당하는 태그만 스타일 속성을 바꾸면 오히려 아이콘이 어그러지는 걸 확인할 수 있었습니다

2021-09-13 10:22 UTC, swon3210 commented on frontend/src/@types/index.ts
> +  type: "team" | "individual";
넵 반영했습니다!

2021-09-13 10:41 UTC, Tanney-102 approved these changes
굳굳 고생하셨습니당!

2021-09-13 11:55 UTC, merged