[#533] 포트폴리오 인수 테스트 작성
woowacourse-teams/2021-pick-git pull request #534
Opened 2021-09-29 05:47 UTC by da-nyee

## 상세 내용
1. 포트폴리오 조회, 수정 API 인수 테스트를 작성했습니다.

| |조회(내 것)|조회(남 것)|수정(내 것)|수정(남 것)|
|:-:|:-:|:-:|:-:|:-:|
|사용자|O|O|O|X|
|게스트|-|O|-|X|

<br/>

2. 프로덕션 버그를 해결했습니다.

- ProjectTag를 생성할 때, Tag id를 전달해서 영속화되지 않았던 문제
- Project - ProjectTag에 대한 연관관계 매핑이 빠져있던 문제

<br/>

## 기타

- 깃들다 팀원들, 매번 잘 도와줘서 감사합니다 ~! 🙇‍♀️

<br/>

Close #533

2021-09-29 05:48 UTC, bperhaps approved these changes
잘 돌아가니까 뿌듯하구만

2021-09-29 05:57 UTC, bperhaps reviewed
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

2021-09-29 06:35 UTC, xlffm3 requested changes
안녕하세요 다니~
포트폴리오 기능 구현 매우 까다로웠을텐데 열심히 구현하느라 고생많으셨어요~

2021-09-29 06:35 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
> +    private final UserRepository userRepository;
사소하긴 한데 당장 이슈 해결에 영향을 주지 않는 부분의 리팩토링이나 패키지 정리, 개행 등 코드 포맷팅은 차라리 나중에 이슈를 등록해서 별도로 pr을 진행하는게 좋을것같아요.
file changed가 너무 많아지는것같습니다.

2021-09-29 06:35 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      public Portfolio toPortfolio(PortfolioRequestDto portfolioRequestDto) {
엔티티에 Builder를 사용하는것도 논의 해봐야겠네요.

2021-09-29 06:35 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/Portfolio.java
> +    private LocalDateTime updatedAt;
신규 컬럼이 추가되었는데 flyway script는 적용이 안되어있네요.
로컬 환경에서 docker로 mariadb 띄우고 dev profile로 실행하면 scheme validation 에러가 발생합니다.

2021-09-29 06:35 UTC, xlffm3 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/portfolio/PortfolioAcceptanceTest.java
> +            @DisplayName("내 것 O")
내 것 0, 남 것 0에 대한 의미가 코드상으로 볼 때 명확하게 이해되지 않습니다. @DisplayName에 부연 설명이 필요해보입니다.

2021-09-29 17:31 UTC, bperhaps reviewed
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

2021-09-30 04:27 UTC, yjksw approved these changes
아무래도 신경쓸 부분이 정말 많네요 ~~!! 
꼼꼼하게 잘 구현해주셔서 감사합니다 😀

2021-09-30 04:27 UTC, yjksw commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/common/UpdateUtil.java
> +        List<UpdatableProxy<T>> sourceProxies = toProxy(sources);
프록시로 한번 감싸서 업데이트를 진행하는 이유는 뭔가요 ?

2021-09-30 09:41 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/contact/Contact.java
> +        return hashCode();
클라이언트에서 넘어오는 태그의 id는 Tag 엔티티의 id인데, 서버에서 사용하는 태그의 id는 ProjectTag 엔티티의 id여서 equals(), hashCode()로 비교할 수 없었어요.
UpdateUtil에 객체를 수정하기 위한 로직들이 있는데, 여기서 contains()와 같은 메소드로 객체의 존재유무를 판단해요.
태그의 경우 id로 비교하면 Tag와 ProjectTag간의 id 불일치 현상으로 객체 존재유무를 판단할 수 없어, 의미론적으로 동일하면 같은 객체라고 여기기 위해서 추가했어요! 즉, Tag와 ProjectTag의 name이 일치하면 같은 객체라고 생각하고 수정 로직을 진행합니다!

2021-09-30 11:43 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      public Portfolio toPortfolio(PortfolioRequestDto portfolioRequestDto) {
Bilder를 사용하게 되면 원하는대로 객체를 제어하기가 힘든것같아요. DTO의 경우는 괜찮지만 Entity와 같이 조금 민감함 객체는 직접 정의하는편이 좋은 것 같아요.

2021-09-30 11:43 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      public Portfolio toPortfolio(PortfolioRequestDto portfolioRequestDto) {
Bilder를 사용하게 되면 원하는대로 객체를 제어하기가 힘든것같아요. DTO의 경우는 괜찮지만 Entity와 같이 조금 민감함 객체는 직접 정의하는편이 좋은 것 같아요.

2021-09-30 11:44 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      private ProjectTag toTag(TagRequestDto tagRequestDto) {
tagRequest로 들어온 Tag와 관련된 데이터를 ProjectTag로 변환시키는 역할을 합니다. 몰랐는데 메서드명이 변경되어 있었네요.

2021-09-30 11:44 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      private ProjectTag toTag(TagRequestDto tagRequestDto) {
tagRequest로 들어온 Tag와 관련된 데이터를 ProjectTag로 변환시키는 역할을 합니다. 몰랐는데 메서드명이 변경되어 있었네요.

2021-09-30 11:47 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      public PortfolioResponseDto toPortfolioResponseDto(Portfolio portfolio) {
로직중 제일오래걸림....

2021-09-30 11:58 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/common/UpdateUtil.java
> +        List<UpdatableProxy<T>> sourceProxies = toProxy(sources);
프록시 객체 내부를 보게 되면 equals와 hashcode를 Updatable의 semanticallyEquals, semanticallyHashcode로 위임시킵니다. 이 과정이 필요한 이유는 다음과 같습니다.

Update를 하는데 있어 생성, 삭제, 변경 관련 로직을 Entity의 id값에 의존해서 진행하게 됩니다(JCF를 사용하기 때문에 equals와 hashcode에 의존하는 형태입니다.). 예를들어 기존의 List에는 존재하지만 새로 들어온 List에는 특정 객체가 없다면 이는 삭제된 Entity이다, 와 같은 로직을 이용합니다.

이때 문제점은 ProjectTag에 있습니다. 사용자는 Tag데이터를 Post에서 받아오고 이를 Portfolio로 전송합니다. 따라서 Portfolio로 전송되는 Tag 관련 데이터는 ProjectTag가 아닌 Tag 그 자체의 데이터를 의미하게 됩니다. 따라서 Portfolio와 연관된 ProjectTag의 값을 업데이트 하기 위해 요청으로 들어온 Tag id를 업데이트를 위한 비교 대상으로 사용하지 못합니다. 

실제 구현체의 구조를 봤을 때 Project - ProjectTag - Tag 로 연관관계가 이어지지만 도메인 모델상으로 봤을때는 Project - Tag 형태를 띠고 있습니다.  즉, ProjectTag는 Tag 그 자체를 의미하는 중간테이블 그 이상, 이하의 의미도 없습니다. 따라서 의미론적 equals와 hashcode를 만들어서 이러한 파라독스를 제거하기 위해 Proxt가 존재하며 위의 의미론적 equals와 hashcode가 존재하게 됩니다.

이해 안가면 다시 물어봐주세요.

2021-09-30 12:53 UTC, yjksw commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/common/UpdateUtil.java
> +        List<UpdatableProxy<T>> sourceProxies = toProxy(sources);
파라독스 제거를 위한 프록시 이군요! 위에 semanticallyEquals 부분도 해당 메소드가 의미가 있는 PostTag가 아닌 Contact 등을 먼저 보았을 때 어떤 의미인지 잘 이해를 못했었는데 이 부분도 PostTag의 여파였네요 .. 다대다 관계가 정말 복잡한게 느껴지네요 

의미론적으로 보았을 때 현재 설계대로 객체간 파라독스도 제거하고 알맞은거 같은데 PostTag의 여파가 너무 큰 것 같기도 하다는 생각이 드네요. 만일 Updatable 한 필드가 더 많았으면 요것 하나 때문에 다 인터페이스를 구현하고 그 객체들에겐 작용을 하지 않는 semanticallyEquals가 추가되어야 하는 것 같기두 하고.. 그냥 제가 코드 보는 시야가 좀 좁은거 같기도 하고 ㅋㅋ 어렵네요 !! 멋있게 잘 풀었다고 생각합니다~!

2021-09-30 14:03 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      public Portfolio toPortfolio(PortfolioRequestDto portfolioRequestDto) {
인정합니다.

2021-09-30 14:04 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      public Portfolio toPortfolio(PortfolioRequestDto portfolioRequestDto) {
아, 그런데 지금처럼 생성자에 약간의 로직이 들어간 경우에는 사용하기 곤란하겠군요 패스.

2021-09-30 15:26 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/dto/PortfolioDtoAssembler.java
>      public Portfolio toPortfolio(PortfolioRequestDto portfolioRequestDto) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 
그거 그냥 AllArgumentConstructor 직접 만들어서 내부에 정의하면 되지 않나??? 빌더 구조상 될것같은데!

2021-09-30 15:26 UTC, bperhaps commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/Portfolio.java
> +    private LocalDateTime updatedAt;
@da-nyee 해줘!

2021-09-30 15:26 UTC, bperhaps commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/portfolio/PortfolioAcceptanceTest.java
> +            @DisplayName("내 것 O")
@da-nyee 해줘!

2021-09-30 15:30 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/Portfolio.java
> +    private LocalDateTime updatedAt;
@bperhaps 할 거야!

2021-09-30 15:30 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/portfolio/PortfolioAcceptanceTest.java
> +            @DisplayName("내 것 O")
@bperhaps 할 거야!

2021-10-01 02:00 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
> +    private final UserRepository userRepository;
넵 유의하겠습니다 ~!

2021-10-01 03:15 UTC, bperhaps reviewed
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Test failure

2021-10-01 04:37 UTC, bperhaps reviewed
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

2021-10-01 04:46 UTC, bperhaps reviewed
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Cool! All passes! - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

2021-10-01 05:40 UTC, xlffm3 approved these changes
flyway 잘 적용됬네요. 확인했습니다!

2021-10-01 06:05 UTC, binghe819 approved these changes
후.. 힘든 구현하시느라 고생 많으셨어요ㅠㅠ

코드만봐도 생각을 짜내서 한 게 보이네요! 고생 많으셨습니다!

몇 가지 궁금한 점들 남겨요~ 일단 머지하고 편하게 의견 달아주셔도 좋을 것 같아요!

2021-10-01 06:05 UTC, binghe819 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/common/UpdatableProxy.java
> +public class UpdatableProxy<T extends Updatable<T>> {
이야.. 한번 차근차근 다시 보고 이해해야겠군요..

2021-10-01 06:09 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/Portfolio.java
> +    private LocalDateTime updatedAt;
프론트에서 값을 보내주면, update()에서 갱신합니다 ~!

2021-10-01 06:12 UTC, bperhaps reviewed
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Cool! All passes! - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

2021-10-01 06:13 UTC, merged