[#76] 로그인 기능 리팩토링 및 테스트 추가
woowacourse-teams/2021-pick-git pull request #80
Opened 2021-07-12 13:53 UTC by binghe819

## 상세 내용
* 리팩토링 내용
  * URL앞에 `/api` 추가
  * 로그인 관련 요청 반환값으로 json 형식이 반환되도록 리팩토링
* 테스트 추가
  * 슬라이스 테스트
  * 통합 테스트
  * OAuth Access Token 저장소 테스트
  * 인수테스트 완성되는대로 커밋할게유~

<br>

## 기타
* 테스트가 원활하게 돌아가려면 `test` yml 파일을 설정해주어야 합니다! 슬랙에 있는 것을 참고하세유

<br>

## ps. 리팩토링했으면 하는 부분이나 테스트 추가했으면 하는 부분있으면 알려주세요~

2021-07-12 16:37 UTC, da-nyee requested changes
테스트 코드 짜면서 마크 코드 참고하고 있었는데,
피드백 남기고 싶은 게 있어서 먼저 하나 작성합니다 !!

2021-07-12 16:37 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
> +        assertThat(appUser).isInstanceOf(GuestUser.class);
```suggestion
        // when
        AppUser appUser = oAuthService.findRequestUserByToken(null);

        // then
        assertThat(appUser.isGuest()).isTrue();
```

`isInstanceOf()` 대신 다형성을 활용해보는 건 어떨까요?

2021-07-12 17:34 UTC, binghe819 commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
> +        assertThat(appUser).isInstanceOf(GuestUser.class);
오~ 굳굳!! 수정할게유!

2021-07-13 07:17 UTC, da-nyee approved these changes
안녕하세요 마크!
구현 수고하셨습니다 👍

Merge 이후 추가 리팩토링 부탁드립니다 ~!

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/dto/OAuthProfileResponse.java
> +    public OAuthProfileResponse() {
```suggestion
    private OAuthProfileResponse() {
```

접근 제어자 변경해주세요 ~!

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/JwtTokenProviderImpl.java
> +    public JwtTokenProviderImpl() {
```suggestion
    private JwtTokenProviderImpl() {
```

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/dto/OAuthLoginUrlResponse.java
> +    public OAuthLoginUrlResponse() {
```suggestion
    private OAuthLoginUrlResponse() {
```

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/dto/OAuthTokenResponse.java
> +    public OAuthTokenResponse() {
```suggestion
    private OAuthTokenResponse() {
```

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/IgnoreAuthenticationInterceptor.java
> +
```suggestion
    private boolean isPreflightRequest(HttpServletRequest request) {
        return isOptions(request)
        && hasAccessControlRequestHeaders(request)
        && hasAccessControlRequestMethod(request)
        && hasOrigin(request);
    }
```

이렇게 개행하면 보기 더 편할 것 같습니다!

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/OAuthAcceptanceTest.java
> +        when(oAuthClient.getLoginUrl()).thenReturn("https://github.com/login/oauth/authorize?");
[테코블 - Mockito와 BDDMockito는 뭐가 다를까?](https://woowacourse.github.io/tecoble/post/2020-09-29-compare-mockito-bddmockito/) 글을 참고해주세요 ~!

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/OAuthAcceptanceTest.java
> +        System.out.println(token);
이 부분 추후에 리팩토링 부탁드립니다 !

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
> +        assertThat(appUser).isInstanceOf(LoginUser.class);
```suggestion
        assertThat(appUser.isGuest()).isFalse();
```

여기도 다형성을 활용해주세요!

2021-07-13 07:17 UTC, da-nyee commented on backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
> +        assertThat(appUser.getAccessToken()).isEqualTo(accessToken);
```suggestion
        assertThat(appUser)
            .usingRecursiveComparison()
            .isEqualTo(XXX)
```

이런 방식으로 코드 변경할 수 있을 거 같아요 !

2021-07-13 07:18 UTC, xlffm3 approved these changes
일단 시급한 모듈이니깐 approve드릴게요.
인터셉터 등 부족한 부분에 대해서는 추후 리팩토링 등록하시면 될것같습니다.

2021-07-13 07:18 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
final

2021-07-13 07:18 UTC, xlffm3 commented on backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/JwtTokenProviderImpl.java
> +
안쓰는 생성자는 private으로 닫아도 될 듯 합니다.

2021-07-13 07:18 UTC, merged

2021-07-13 07:25 UTC, binghe819 commented
접근제어자 잘 설정하자.